app/models/products.py
from app.dbcon import db
from app.models.purchase import ProductPurchaseOrder, PurchaseOrder
from app.models.issue import ProductIssueOrder


# define the product model
class Products(db.Model):
    __tablename__ = 'products'

    id = db.Column(db.Integer, primary_key=True)
    product_name = db.Column(db.String(50), nullable=False)
    product_category = db.Column(db.String(50), nullable=False)
    uom = db.Column(db.String(50), nullable=False)
    unit_price = db.Column(db.Float, nullable=False)
    quantity = db.Column(db.Integer, nullable=False)
    reorder_level = db.Column(db.Integer, nullable=False)

    purchase_order = db.relationship('ProductPurchaseOrder', backref='products', lazy='dynamic', cascade='all, delete')
    issue_order = db.relationship('ProductIssueOrder', backref='products', lazy='dynamic', cascade='all, delete')


    def __repr__(self):
        return '{}: Available Quantity={}'.format(self.product_name, self.quantity)

app/manage_product/routes.py
from flask import Blueprint
from flask import render_template, url_for, redirect, request, flash
from app.dbcon import db
from flask_login import login_required, current_user
from app.manage_product.form import NewProductForm, EditProductForm

product_bp = Blueprint('product_bp', __name__, url_prefix='/products')


from app.models.products import Products

@product_bp.route('/')
@login_required
def products_list():
    products = Products.query.all()    
    return render_template('products/products_list.html', title='Products List', products=products)


@product_bp.route('/add_product', methods=['GET', 'POST'])
@login_required
def add_product():
    form = NewProductForm()
    if form.validate_on_submit():
        new_product = Products(product_name=form.product_name.data, product_category=form.product_category.data, uom=form.uom.data, unit_price=form.unit_price.data, quantity=form.quantity.data, reorder_level=form.reorder_level.data)
        db.session.add(new_product)
        db.session.commit()
        flash('Product: {} added to the database!'.format(form.product_name.data), 'success')
        return redirect(url_for('product_bp.add_product'))
        
    return render_template('products/add_product.html', title='Add Product', form=form, legend='Add New Product')


@product_bp.route('/<int:id>', methods=('GET', 'POST'))
@login_required
def products(id):
    product = Products.query.filter_by(id=id).first()
    return render_template('products/product.html', title='Product Detail', product=product)    
   

@product_bp.route('/<int:id>/edit', methods=('GET', 'POST'))
@login_required
def edit_products(id):
    product = Products.query.filter_by(id=id).first()
    if current_user.role != 'store_keeper' and current_user.role !='admin':
        flash('Action not allowed!')
        return redirect(url_for('index'))
    form = EditProductForm()
    if form.validate_on_submit():
        product.product_name = form.product_name.data
        product.product_category = form.product_category.data
        product.uom = form.uom.data
        product.unit_price = form.unit_price.data
        product.quantity = form.quantity.data
        product.reorder_level = form.reorder_level.data
        db.session.commit()
        flash('Product: {} has been updated!'.format(form.product_name.data), 'success')
        return redirect(url_for('product_bp.products', id=product.id))
    
    elif request.method == 'GET':
        form.product_name.data = product.product_name
        form.product_category.data = product.product_category
        form.uom.data = product.uom
        form.unit_price.data = product.unit_price
        form.quantity.data = product.quantity
        form.reorder_level.data = product.reorder_level
    return render_template('products/add_product.html', title='Edit Product', form=form, legend='Edit Product')


@product_bp.route('/<int:id>/delete', methods=('GET', 'POST'))
@login_required
def delete_products(id):
    product = db.get_or_404(Products, id)
    if current_user.role != 'store_keeper' and current_user.role !='admin':
        flash('Action not allowed!', 'danger')
        return redirect(url_for('index'))
    db.session.delete(product)
    db.session.commit()
    flash('Product {} has been deleted!'.format(product.product_name), 'success')
    return redirect(url_for('product_bp.products_list'))

app/templates/products/add_product.html
{% extends 'base.html' %}

{% block content %}

<div class="container justify-content-center col-md-4">
      <form action="" method="post" novalidate>
        {{ form.hidden_tag() }}
        <legend class="border-bottom">{{ legend }}</legend>
            <div class="form-group">
              {{ form.product_name.label(class="form-control-label") }}
              {{ form.product_name(class="form-control form-control-lg") }}
              {% for error in form.product_name.errors %}
              <span style="color: red;">[{{ error }}]</span>
              {% endfor %}
            </div>

            <div class="form-group">
              {{ form.product_category.label(class="form-control-label") }}
              {{ form.product_category(class="form-control form-control-lg") }}
              {% for error in form.product_category.errors %}
              <span style="color: red;">[{{ error }}]</span>
              {% endfor %}
            </div>

            <div class="form-group">
              {{ form.uom.label(class="form-control-label") }}
              {{ form.uom(class="form-control form-control-lg") }}
              {% for error in form.uom.errors %}
              <span style="color: red;">[{{ error }}]</span>
              {% endfor %}
            </div>

            <div class="form-group">
              {{ form.unit_price.label(class="form-control-label") }}
              {{ form.unit_price(class="form-control form-control-lg") }}
              {% for error in form.unit_price.errors %}
              <span style="color: red;">[{{ error }}]</span>
              {% endfor %}
            </div>

            <div class="form-group">
              {{ form.quantity.label(class="form-control-label") }}
              {{ form.quantity(class="form-control form-control-lg") }}
              {% for error in form.quantity.errors %}
              <span style="color: red;">[{{ error }}]</span>
              {% endfor %}
            </div>
            <div class="form-group">
              {{ form.reorder_level.label(class="form-control-label") }}
              {{ form.reorder_level(class="form-control form-control-lg") }}
              {% for error in form.reorder_level.errors %}
              <span style="color: red;">[{{ error }}]</span>
              {% endfor %}
            </div>
            
            <div class="form-group">{{ form.submit(class='btn btn-outline-info mt-3') }}</div>
    </form>
</div>

{% endblock %}

app/templates/products/product.html
{% extends 'base.html' %}

{% block content %}

<div class="card mt-5">
    <div class="card-title bg-dark text-light">
        <div class="title-block text-center">
            {{ title }}
        </div>
    </div>
    <div class="card-body">
        <h1 class="text-center">{{ product.product_name }}</h1>
        <h5 class="text-center">{{ product.product_category }}</h5>
        <h5 class="text-center">{{ product.unit_price }}</h5>
        <h5 class="text-center">{{ product.reorder_level }}</h5>
    </div>
</div>
 


{% endblock %}

app/templates/products/products_list.html
{% extends 'base.html' %}

{% block content %}

<!-- products.html -->
<div class="container">
    <div class="table-responsive">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Product Name</th>
                    <th>Category</th>
                    <th>Price</th>
                    <th>Quantity</th>
                </tr>
            </thead>
        <tbody>
            {% for product in products %}
            <tr>
                <td><a href="{{ url_for('product_bp.products', id=product.id) }}">{{ product.product_name }}</a></td>
                <td>{{ product.product_category }}</td>
                <td>{{ product.unit_price }}</td>
                <td>{{ product.quantity }}</td>
                <td>
                    <a href="{{ url_for('product_bp.edit_products', id=product.id) }}" class="btn btn-primary btn-sm" style="margin-right: 1.5rem;">Edit</a>
                    <a href="{{ url_for('product_bp.delete_products', id=product.id) }}" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#deleteProductModal">Delete</a>   
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
</div>



{% endblock %}