app/models/purchase.py
from datetime import datetime
from app.dbcon import db
from flask_login import current_user

# define a junction class between purchase order product table
class ProductPurchaseOrder(db.Model):
    __tablename__ = 'product_purchase_order'
    
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    purchase_order_id = db.Column(db.Integer, db.ForeignKey('purchase_order.id'), nullable=False)
    product_id = db.Column(db.Integer, db.ForeignKey('products.id'), nullable=False)
    quantity = db.Column(db.Integer, nullable=False)


    def __repr__(self):
        return '<ProductPurchaseOrder (PurchaseOrder={}, Product={}, Quantity={})>'.format(
                self.purchase_order_id, self.product_id, self.quantity)


# define the purchaseorder model
class PurchaseOrder(db.Model):
    __tablename__ = 'purchase_order'
    
    id = db.Column(db.Integer, primary_key=True)
    order_date = db.Column(db.Date, nullable=False, default=datetime.now().date())
    created_by = db.Column(db.Integer, db.ForeignKey('users.id'))
    supplier = db.Column(db.String(50))
    status = db.Column(db.String(20), nullable=False, default='created')

    users = db.relationship('Users', backref='purchase_order')   
    products = db.relationship('ProductPurchaseOrder', backref='purchase_order', lazy='dynamic', cascade='all, delete') 


    def __repr__(self):
        return '<Purchase Order: ID={} User ID={}: Status={}>'.format(self.id, self.created_by, self.status)

app/manage_purchase/routes.py
from datetime import datetime
from flask import Blueprint
from flask import render_template, url_for, request, redirect, flash
from app.dbcon import db
from flask_login import login_required, current_user
from app.models.purchase import PurchaseOrder, ProductPurchaseOrder
from app.manage_purchase.form import PurchaseForm, ProductForm, EditPurchaseForm
from app.models.products import Products


purchase_bp = Blueprint('purchase_bp', __name__, url_prefix='/purchase')


@purchase_bp.route('/')
@login_required
def purchase_list():
    purchase_orders = PurchaseOrder.query.all()
    return render_template('purchase/purchase_list.html', title='Purchase List', purchase_orders=purchase_orders)
    

@purchase_bp.route('/create_purchase_order', methods=('GET', 'POST'))
@login_required
def create_purchase_order():
    form = PurchaseForm()

    if request.method == 'POST':
        if form.validate_on_submit():
            # create the purchase order instance
            purchase_order = PurchaseOrder(created_by=current_user.id, supplier=form.supplier.data, status=form.status.data)
            db.session.add(purchase_order)
            db.session.commit()    
            for entry in form.products.entries:
                if entry.form.product.data:
                    product_id = entry.form.product.data
                    quantity = entry.form.quantity.data

                    product_purchase_order = ProductPurchaseOrder(
                        purchase_order_id=purchase_order.id,
                        product_id=product_id,
                        quantity=quantity
                        )
                    
                    db.session.add(product_purchase_order)
                   
        
            db.session.commit()

            flash('Purchase Order{} created successfully'.format(purchase_order.id))
            return redirect(url_for('purchase_bp.purchase_list'))
        else:
            print('Form validation error', form.errors)
    
    else:
        return render_template('/purchase/new_purchase.html', title='Create Purchase Order', form=form)


@purchase_bp.route('/<int:id>', methods=('GET', 'POST'))
@login_required
def product_purchase_order(id):
    products_purchase = ProductPurchaseOrder.query.filter_by(id=id).first()
    product = Products.query.filter_by(id=products_purchase.product_id).first()
    return render_template('purchase/purchase_detail.html', title='Purchase Order Detail', products_purchase=products_purchase, product=product)    


@purchase_bp.route('/<int:id>/edit', methods=('GET', 'POST'))
@login_required
def edit_purchase_order(id):
    purchase_order = PurchaseOrder.query.filter_by(id=id).first()
    if current_user.role != 'manager' and current_user.role !='admin':
        flash('You are not allowed to perform this action!', 'danger')
        return redirect(url_for('index'))
    form = EditPurchaseForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            # update the purchase order instance
            purchase_order.supplier = form.supplier.data
            purchase_order.status = form.status.data
            db.session.commit()
            flash('Purchase Order {} status has been changed to {}'.format(purchase_order.id, purchase_order.status), 'success')
            product_purchase_order = ProductPurchaseOrder.query.filter_by(id=purchase_order.id).first()
            if purchase_order.status == 'purchased':
                product = Products.query.filter_by(id=product_purchase_order.product_id).first()
                purchase_quantity = product_purchase_order.quantity
                new_quantity = product.quantity + purchase_quantity
                product.quantity = new_quantity
                db.session.commit()
                flash('{} {} has been purchased'.format(product_purchase_order.quantity, product_purchase_order.product_id), 'success')
                return redirect(url_for('product_bp.products_list'))
                   
            return redirect(url_for('purchase_bp.product_purchase_order', id=purchase_order.id))
        
    elif request.method == 'GET':
        form.supplier.data = purchase_order.supplier
        form.status.data = purchase_order.status
            
    return render_template('/purchase/edit_purchase.html', title='Edit Purchase Order', form=form, id=id)

app/templates/purchase/edit_purchase.html
{% extends 'base.html' %}

{% block content %}

<form method="POST" action="{{ url_for('purchase_bp.edit_purchase_order', id=id) }}">
  {{ form.csrf_token }}
  
  <h2>Edit Purchase Order</h2>
  <div>
    {{ form.supplier.label }}
    {{ form.supplier(class="form-control") }}
  </div>
  <div>
     {{ form.status.label }}
     {{ form.status(class="form-control") }}
  </div>
  
  {{ form.submit(class="btn btn-primary") }}
</form>


{% endblock %}

app/templates/purchase/new_purchase.html
{% extends 'base.html' %}

{% block content %}

<form method="POST" action="{{ url_for('purchase_bp.create_purchase_order') }}">
  {{ form.csrf_token }}
  
  <h2>Create Purchase Order</h2>
  
  {{ form.supplier.label }}
  {{ form.supplier(class="form-control") }}
  
  <div id="products-container">
    {% for field in form.products %}
      <div class="product-entry">
        {{ field.form.product.label }}
        {{ field.form.product(class="form-control") }}
        {{ field.form.quantity.label }}
        {{ field.form.quantity(class="form-control") }}
        {% if loop.index > 0 %}
          <button type="button" class="btn btn-danger remove-product">Remove</button>
        {% endif %}
      </div>
    {% endfor %}
  </div>
  
  <button type="button" class="btn btn-primary" id="add-product">Add Product</button>
  <br><br>
  
  {{ form.submit(class="btn btn-primary") }}
</form>


<script src="{{ url_for('static', filename='js/script.js') }}"></script>

{% endblock %}

app/templates/purchase/purchase_detail.html
{% extends 'base.html' %}

{% block content %}

<div class="card mt-5">
    <div class="card-title bg-dark text-light">
        <div class="title-block text-center">
            {{ title }}
        </div>
    </div>
    <div class="card-body">
        <h5 class="text-center">Product: {{ product.product_name }}</h5>
        <h5 class="text-center">Qunatity: {{ products_purchase.quantity }}</h5>
    </div>
    <a href="{{ url_for('purchase_bp.edit_purchase_order', id=products_purchase.id)}}" class="btn btn-primary btn-sm" style="margin-right: 1.5rem;">Edit</a>
</div>
 


{% endblock %}

app/templates/purchase/purchase_list.html
{% extends 'base.html' %}

{% block content %}

<!-- purchase list table -->

<div class="container">
<div class="table-responsive">	
    <table class="table table-striped">
	<thead>
	    <tr>
		<th>PO ID</th>
		<th>Date</th>
		<th>Created By</th>
		<th>Supplier</th>
		<th>Status</th>	
	    </tr>		
	</thead>	
	<tbody>
		{% for po in purchase_orders %}			
		<tr>
		    <td><a href="">{{ po.id }}</a></td>
		    <td>{{ po.order_date }}</td>			
		    <td>{{ po.created_by }}</td>		
		    <td>{{ po.supplier }}</td>
		    <td>{{ po.status }}</td>
		    <td>
			<a href="{{ url_for('purchase_bp.product_purchase_order', id=po.id)}}" class="btn btn-primary btn-sm" style="margin-right: 1.5rem;">Detail</a>	
		    </td>
		
		</tr>
		{% endfor %}	
	</tbody>
			
    </table>
</div>
</div>

{% endblock %}