app/manage_issue/routes.py
from flask import Blueprint
from flask import render_template, url_for, request, redirect
from app.dbcon import db


issue_bp = Blueprint('issue_bp', __name__, url_prefix='/issue')


@issue_bp.route('/')
def index():
   
    return "<h1>This is from Issue Blueprint</h1>"
    #return render_template(url_for('user.html'))

app/manage_purchase/routes.py
from datetime import datetime
from flask import Blueprint
from flask import render_template, url_for, request, redirect, flash
from app.dbcon import db
from flask_login import login_required, current_user
from app.models.purchase import PurchaseOrder, ProductPurchaseOrder
from app.manage_purchase.form import PurchaseForm, ProductForm, EditPurchaseForm
from app.models.products import Products


purchase_bp = Blueprint('purchase_bp', __name__, url_prefix='/purchase')


@purchase_bp.route('/')
@login_required
def purchase_list():
    purchase_orders = PurchaseOrder.query.all()
    return render_template('purchase/purchase_list.html', title='Purchase List', purchase_orders=purchase_orders)
    

@purchase_bp.route('/create_purchase_order', methods=('GET', 'POST'))
@login_required
def create_purchase_order():
    form = PurchaseForm()

    if request.method == 'POST':
        if form.validate_on_submit():
            # create the purchase order instance
            purchase_order = PurchaseOrder(created_by=current_user.id, supplier=form.supplier.data, status=form.status.data)
            db.session.add(purchase_order)
            db.session.commit()    
            for entry in form.products.entries:
                if entry.form.product.data:
                    product_id = entry.form.product.data
                    quantity = entry.form.quantity.data

                    product_purchase_order = ProductPurchaseOrder(
                        purchase_order_id=purchase_order.id,
                        product_id=product_id,
                        quantity=quantity
                        )
                    
                    db.session.add(product_purchase_order)
                   
        
            db.session.commit()

            flash('Purchase Order{} created successfully'.format(purchase_order.id))
            return redirect(url_for('purchase_bp.purchase_list'))
        else:
            print('Form validation error', form.errors)
    
    else:
        return render_template('/purchase/new_purchase.html', title='Create Purchase Order', form=form)


@purchase_bp.route('/<int:id>', methods=('GET', 'POST'))
@login_required
def product_purchase_order(id):
    products_purchase = ProductPurchaseOrder.query.filter_by(id=id).first()
    product = Products.query.filter_by(id=products_purchase.product_id).first()
    return render_template('purchase/purchase_detail.html', title='Purchase Order Detail', products_purchase=products_purchase, product=product)    


@purchase_bp.route('/<int:id>/edit', methods=('GET', 'POST'))
@login_required
def edit_purchase_order(id):
    purchase_order = PurchaseOrder.query.filter_by(id=id).first()
    if current_user.role != 'manager' and current_user.role !='admin':
        flash('You are not allowed to perform this action!', 'danger')
        return redirect(url_for('index'))
    form = EditPurchaseForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            # update the purchase order instance
            purchase_order.supplier = form.supplier.data
            purchase_order.status = form.status.data
            db.session.commit()
            flash('Purchase Order {} status has been changed to {}'.format(purchase_order.id, purchase_order.status), 'success')
            product_purchase_order = ProductPurchaseOrder.query.filter_by(id=purchase_order.id).first()
            if purchase_order.status == 'purchased':
                product = Products.query.filter_by(id=product_purchase_order.product_id).first()
                purchase_quantity = product_purchase_order.quantity
                new_quantity = product.quantity + purchase_quantity
                product.quantity = new_quantity
                db.session.commit()
                flash('{} {} has been purchased'.format(product_purchase_order.quantity, product_purchase_order.product_id), 'success')
                return redirect(url_for('product_bp.products_list'))
                   
            return redirect(url_for('purchase_bp.product_purchase_order', id=purchase_order.id))
        
    elif request.method == 'GET':
        form.supplier.data = purchase_order.supplier
        form.status.data = purchase_order.status
            
    return render_template('/purchase/edit_purchase.html', title='Edit Purchase Order', form=form, id=id)

app/manage_users/routes.py
from flask import Blueprint
from flask import render_template, flash, url_for, request, redirect
from app.dbcon import db
from app.manage_users.form import LoginForm, RegistrationForm, EditAccountForm
from flask_login import login_user, logout_user, current_user, login_required
from werkzeug.security import generate_password_hash, check_password_hash


# create a blueprint for the users management
users_bp = Blueprint('users_bp', __name__, url_prefix='/users')

from app.models.users import Users


@users_bp.route('/login', methods=('GET', 'POST'))
def login():
    if current_user.is_authenticated:
        return redirect(url_for('index'))
    form = LoginForm()
    if form.validate_on_submit():
        user = Users.query.filter_by(username=form.username.data).first()
        if user and check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember_me.data)
            next_page = request.args.get('next')
            flash('Welcome ({})'.format(user.name), 'success')
            return redirect(next_page) if next_page else redirect(url_for('dashboard'))
        else:
            flash('Login Unsuccessful, please check your Username or Password', 'danger')
        
    return render_template(('users_auth/login.html'), title='Sign In', form=form)


@users_bp.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('index'))


@users_bp.route('/add_user', methods=['GET', 'POST'])
@login_required
def add_user():
    form = RegistrationForm()
    if form.validate_on_submit():
        new_user = Users(name=form.name.data, username=form.username.data,
                         password=generate_password_hash(form.password.data, method='sha256'), role=form.role.data)
        db.session.add(new_user)
        db.session.commit()
        flash('Account created for {}!'.format(form.username.data), 'success')
        return redirect(url_for('users_bp.users_list'))
        
    return render_template('users_auth/add_user.html', title='Add User', form=form)


@users_bp.route('/account', methods=('GET', 'POST'))
@login_required
def account():
    form = EditAccountForm()
    if form.validate_on_submit():
        current_user.name = form.name.data
        current_user.username = form.username.data
        current_user.role = form.role.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users_bp.users_list'))
    elif request.method == 'GET':
        form.name.data = current_user.name
        form.username.data = current_user.username
        form.role.data = current_user.role

    return render_template('users_auth/account.html', title='Edit User Account', form=form)


@users_bp.route('/')
@login_required
def users_list():
    user_list = Users.query.all()
    return render_template('/users_auth/users_list.html', title='Users List', user_list=user_list)


@users_bp.route('/<int:id>/delete', methods=('GET', 'POST'))
@login_required
def delete_user(id):
    user = db.get_or_404(Users, id)
    if current_user.role != 'admin':
        flash('Action not allowed!', 'danger')
        return redirect(url_for('users_bp.users_list'))
    db.session.delete(user)
    db.session.commit()
    flash('User {} has been deleted!'.format(user.name), 'success')
    return redirect(url_for('users_bp.users_list'))

app/templates/add_user.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
<!-- 
        {% if error %}
            <div class="alert alert-danger">{{ error }}</div>
        {% endif %}
 -->
        <form action="/users/add_user" method="POST">
          {{ form.hidden_tag() }}
          <fieldset class="form-group mb-3">
            <legend class="border-bottom">Create New User</legend>
            <div class="form-group">
              {{ form.name.label(class="form-control-label") }}
              {{ form.name(class="form-control form-control-lg") }}
            </div>

            <div class="form-group mb-3">
              {{ form.username.label(class="form-control-label") }}
              {{ form.username(class="form-control form-control-lg") }}
            </div>

            <div class="form-group">
              {{ form.password.label(class="form-control-label") }}
              {{ form.password(class="form-control form-control-lg") }}
            </div>

            <div class="form-group">
              {{ form.confirm_password.label(class="form-control-label") }}
              {{ form.confirm_password(class="form-control form-control-lg") }}
            </div>

            <div class="form-group">
              {{ form.role.label(class="form-control-label") }}
              {{ form.role(class="form-control form-control-lg") }}
            </div>
          </fieldset>

          <div class="form-group">
            {{ form.submit(class="btm btn-outline-info") }}              
          </div>

<!-- 
          <div class="mb-3"><input type="text" class="form-control" name="name" placeholder="Employee Name" required></div>
          <div class="mb-3"><input type="text" class="form-control" name="username" placeholder="User Name" required></div>
          <div class="mb-3"><input type="text" class="form-control" name="password" placeholder="Password"></div>
          <div class="mb-3"> 
            <select class="form-select" name="role" required>
              <option value="" selected disabled>Select Role</option>
              <option value="ADMIN">ADMIN</option>
              <option value="MANAGER">MANAGER</option>
              <option value="STORE_KEEPER">STORE KEEPER</option>
              <option value="USER">USER</option>
            </select> 
          </div>
        <div class="mb-3"><button type="submit"  class="w-100 btn btn-primary">Add User</button></div>
        </form>
      </div> -->
  </div>
</div>

{% endblock %}

app/templates/base.html
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{% block title %}{{ title }}{% endblock %} - Inventory</title>
  <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='css/styles.css') }}" rel="stylesheet">
</head>

<body class="text-center">
  <div class="header">
    <nav class="navbar navbar-expand-lg navbar-dark">
      <a class="navbar-brand" href="{{ url_for('index')}}">Simplify</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto">
          {% if current_user.is_authenticated %}
            {% if current_user.role == 'admin' %}
              <li class="nav-item"><a class="nav-link" href="{{ url_for('users_bp.users_list') }}">Users List</a></li>
              <li class="nav-item"><a class="nav-link" href="{{ url_for('users_bp.add_user') }}">Add User</a></li>
            {% endif %}
          <li class="nav-item"><a class="nav-link" href="{{ url_for('users_bp.account') }}">Profile</a></li>
          <li class="nav-item"><a class="nav-link" href="{{ url_for('users_bp.logout') }}">Sign Out</a></li>
          {% else %}
          <li class="nav-item"><a class="nav-link" href="{{ url_for('users_bp.login') }}">Sign In</a></li>
          {% endif %}
        </ul>
      </div>
    </nav>
  </div>

  <div class="container">
    <div class="row">
      {% if current_user.is_authenticated %}
      <div class="col-md-2 sidebar">
        <ul class="nav flex-column">
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('dashboard') }}">Dashboard</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('product_bp.products_list') }}">List Products</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('product_bp.add_product') }}">Create Product</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('purchase_bp.purchase_list') }}">Purchase Order List</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('purchase_bp.create_purchase_order') }}">New Purchase Orders</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('issue_bp.index') }}">Issue Orders List</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('issue_bp.index') }}">New Issue Orders</a>
          </li>
        </ul>
      </div>
      {% endif %}

      <div class="col-md-10 main-content">
        <div class="content">
          <hr>
          {% with messages = get_flashed_messages(with_categories=true) %}
          {% if messages %}
          {% for category, message in messages %}
          <div class="alert alert-{{ category }}">
            {{ message }}
          </div>
          {% endfor %}
          {% endif %}
          {% endwith %}

          {% block content %}{% endblock %}
        </div>
      </div>
    </div>
  </div>

  <div class="footer">
    <div class="container">
      <span>&copy; 2023</span>
    </div>
  </div>
  
  <script src="{{ url_for('static', filename='js/popper.min.js') }}"></script>
  <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
				
</body>

</html>

app/templates/base2.html
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{% block title %}{{ title }}{% endblock %} Simplify</title>
  <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='css/styles.css') }}" rel="stylesheet">

</head>

<body class="text-center">
  <div class="header">
    <nav class="navbar navbar-expand-lg navbar-dark">
      <a class="navbar-brand" href="{{ url_for('index')}}">Simplify</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto">
          {% if current_user.is_authenticated %}
            {% if current_user.role == 'admin' %}
              <li class="nav-item"><a class="nav-link" href="{{ url_for('users_bp.users_list') }}">Users List</a></li>
                <li class="nav-item"><a class="nav-link" href="{{ url_for('users_bp.add_user') }}">Add User</a></li>
            {% endif %}
          <li class="nav-item"><a class="nav-link" href="{{ url_for('users_bp.account') }}">Profile</a></li>
          <li class="nav-item"><a class="nav-link" href="{{ url_for('users_bp.logout') }}">Sign Out</a></li>
          {% else %}
          <li class="nav-item"><a class="nav-link" href="{{ url_for('users_bp.login') }}">Sign In</a></li>
          {% endif %}
        </ul>
      </div>
    </nav>
  </div>

    <div class="main-content">
        <div class="content">
          <hr>
          {% with messages = get_flashed_messages(with_categories=true) %}
          {% if messages %}
          {% for category, message in messages %}
          <div class="alert alert-{{ category }}">
            {{ message }}
          </div>
          {% endfor %}
          {% endif %}
          {% endwith %}

          {% block content %}{% endblock %}
        </div>
      </div>
    </div>
  </div>

  <div class="footer">
    <div class="container">
      <span>&copy; 2023</span>
    </div>
  </div>

  <script src="{{ url_for('static', filename='js/popper.min.js') }}"></script>
  <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>

</body>

</html>

app/templates/dashboard.html
{% extends 'base.html' %}

{% block content %}

    <!-- Main Content -->
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-10">
                <!-- Display low stock items here -->
                <h3>Low Stock Items</h3>
                <div class="notification-container">
					<div class="table-responsive">
						<table class="table table-striped">
						<thead>
							<tr>
								<th>Product Name</th>
								<th>Category</th>
								<th>Quantity</th>
								<th>Reorder Level</th>
							</tr>
						</thead>
						<tbody>
							{% for n in notification %}
			    			<tr>
								<td>{{ n.product_name }}</td>
								<td>{{ n.product_category }}</td>
								<td>{{ n.quantity }}</td>
								<td>{{ n.reorder_level }}</td>
			    			</tr>
			 				{% endfor %}
				
						</tbody>
						</table>
					</div>
            	</div>
        	</div>   
		</div>
	</div>   

{% endblock %}

app/templates/main.html
{% extends 'base2.html' %}

{% block content %}

    <div class="jumbotron">
        <h2 class="display-4">Simple Inventory Management System!</h2>
        <p class="lead">Simplify and streamline your hotel inventory management with our intuitive application. Easily track products, manage orders, and maintain accurate stock levels.</p>
    </div>
         
        <div class="card">
            <div class="card-header">
                <h3>Key Features:</h3>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-md-3">
                        <div class="card mb-3">
                            <div class="card-body">
                                <h5 class="card-title">Product Management</h5>
                                <p class="card-text">Efficiently create, edit, and delete products in your inventory.</p>
                                <a href="{{ url_for('product_bp.products_list') }}" class="btn btn-outline-info">Product Management</a>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="card mb-3">
                            <div class="card-body">
                                <h5 class="card-title">Purchase Management</h5>
                                <p class="card-text">Seamlessly create purchase orders and manage the procurement process.</p>
                                <a href="{{ url_for('purchase_bp.purchase_list') }}" class="btn btn-outline-info">Purchase Management</a>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="card mb-3">
                            <div class="card-body">
                                <h5 class="card-title">Issue Management</h5>
                                <p class="card-text">Effectively handle product issuance, keeping track of products leaving your inventory.</p>
                                <a href="{{ url_for('issue_bp.index') }}" class="btn btn-outline-info">Issue Management</a>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="card mb-3">
                            <div class="card-body">
                                <h5 class="card-title">Role-Based Access Control</h5>
                                <p class="card-text">Assign different roles to users, such as administrators and staff members.</p>
                                <a href="{{ url_for('users_bp.users_list') }}" class="btn btn-outline-info">User Management</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    <div class="mt-4 text-center">
        <p class="lead">Start managing your hotel inventory today!</p>
        <a href="{{ url_for('users_bp.login')}}" class="btn btn-lg btn-outline-info">Sign In</a>
    </div>
                    
{% endblock %}